import Head from "next/head";
import { useEffect } from "react";
import { Viewer } from "@photo-sphere-viewer/core";

export default function Home() {
  useEffect(() => {
    const baseUrl = "https://photo-sphere-viewer-data.netlify.app/assets/";

    const viewer = new Viewer({
      container: document.querySelector("#panorama-view"),
      panorama: "/pano1.jpg",
      loadingImg: baseUrl + "loader.gif",
      touchmoveTwoFingers: true,
      mousewheelCtrlKey: true,
    });
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
